2024-01-25 13:32:23,453 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-01-25 13:32:23,453 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Configure stats pid to 41296
2024-01-25 13:32:23,453 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Loading settings from C:\Users\jsjon\.config\wandb\settings
2024-01-25 13:32:23,453 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Loading settings from c:\Users\jsjon\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\settings
2024-01-25 13:32:23,453 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-25 13:32:23,453 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'New Code\\Data_extrapolative copy.py', 'program_abspath': 'c:\\Users\\jsjon\\OneDrive\\SKKU\\연구자료\\Catalyst AI_rev\\New Code\\Data_extrapolative copy.py', 'program': 'c:\\Users\\jsjon\\OneDrive\\SKKU\\연구자료\\Catalyst AI_rev\\New Code\\Data_extrapolative copy.py'}
2024-01-25 13:32:23,454 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-01-25 13:32:23,454 INFO    MainThread:41296 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\jsjon\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240125_133223-5ubcgrwi\logs\debug.log
2024-01-25 13:32:23,454 INFO    MainThread:41296 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\jsjon\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240125_133223-5ubcgrwi\logs\debug-internal.log
2024-01-25 13:32:23,454 INFO    MainThread:41296 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001833BF65280>
2024-01-25 13:32:23,455 INFO    MainThread:41296 [wandb_init.py:init():566] calling init triggers
2024-01-25 13:32:23,455 INFO    MainThread:41296 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-01-25 13:32:23,455 INFO    MainThread:41296 [wandb_init.py:init():616] starting backend
2024-01-25 13:32:23,455 INFO    MainThread:41296 [wandb_init.py:init():620] setting up manager
2024-01-25 13:32:23,464 INFO    MainThread:41296 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-01-25 13:32:23,467 INFO    MainThread:41296 [wandb_init.py:init():628] backend started and connected
2024-01-25 13:32:23,490 INFO    MainThread:41296 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-25 13:32:23,491 INFO    MainThread:41296 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-25 13:32:23,491 INFO    MainThread:41296 [wandb_init.py:init():720] updated telemetry
2024-01-25 13:32:23,589 INFO    MainThread:41296 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-01-25 13:32:24,140 INFO    MainThread:41296 [wandb_run.py:_on_init():2254] communicating current version
2024-01-25 13:32:24,199 INFO    MainThread:41296 [wandb_run.py:_on_init():2263] got version response 
2024-01-25 13:32:24,199 INFO    MainThread:41296 [wandb_init.py:init():804] starting run threads in backend
2024-01-25 13:32:37,346 INFO    MainThread:41296 [wandb_run.py:_console_start():2233] atexit reg
2024-01-25 13:32:37,346 INFO    MainThread:41296 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-01-25 13:32:37,347 INFO    MainThread:41296 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-01-25 13:32:37,347 INFO    MainThread:41296 [wandb_run.py:_redirect():2178] Redirects installed.
2024-01-25 13:32:37,347 INFO    MainThread:41296 [wandb_init.py:init():847] run started, returning control to user process
2024-01-25 13:32:37,351 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:32:37,352 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:32:42,060 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:32:42,064 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:32:42,064 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:32:42,683 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:32:42,687 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:32:42,687 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:33:10,397 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:33:10,398 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:33:10,399 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:33:27,743 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:33:27,746 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:33:27,747 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:33:36,455 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:33:36,460 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:33:36,460 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:33:38,521 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:33:38,526 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:33:38,527 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:33:39,631 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:33:39,636 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:33:39,636 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:33:39,817 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:33:39,822 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:33:39,822 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:33:41,974 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:33:41,978 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:33:41,978 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:33:43,018 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:34:24,134 WARNING MsgRouterThr:41296 [router.py:message_loop():77] message_loop has been closed
2024-01-25 13:34:25,565 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:34:25,566 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:35:52,659 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:35:52,673 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:35:52,673 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:35:56,545 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:35:56,555 INFO    MainThread:41296 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:35:56,555 INFO    MainThread:41296 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:36:03,003 INFO    MainThread:41296 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:36:03,036 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-01-25 13:36:03,037 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Configure stats pid to 41296
2024-01-25 13:36:03,037 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Loading settings from C:\Users\jsjon\.config\wandb\settings
2024-01-25 13:36:03,037 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Loading settings from c:\Users\jsjon\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\settings
2024-01-25 13:36:03,037 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-25 13:36:03,037 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'New Code\\Data_extrapolative copy.py', 'program_abspath': 'c:\\Users\\jsjon\\OneDrive\\SKKU\\연구자료\\Catalyst AI_rev\\New Code\\Data_extrapolative copy.py', 'program': 'c:\\Users\\jsjon\\OneDrive\\SKKU\\연구자료\\Catalyst AI_rev\\New Code\\Data_extrapolative copy.py'}
2024-01-25 13:36:03,038 INFO    MainThread:41296 [wandb_setup.py:_flush():76] Applying login settings: {'api_key': '***REDACTED***'}
2024-01-25 13:36:03,038 INFO    MainThread:41296 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\jsjon\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240125_133603-iw3chmbc\logs\debug.log
2024-01-25 13:36:03,038 INFO    MainThread:41296 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\jsjon\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240125_133603-iw3chmbc\logs\debug-internal.log
2024-01-25 13:36:03,038 INFO    MainThread:41296 [wandb_init.py:init():566] calling init triggers
2024-01-25 13:36:03,038 INFO    MainThread:41296 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-01-25 13:36:03,038 INFO    MainThread:41296 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 5ubcgrwi
2024-01-25 13:36:03,167 ERROR   MainThread:41296 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 601, in init
    latest_run.finish()
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1953, in finish
    return self._finish(exit_code, quiet)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1961, in _finish
    tel.feature.finish = True
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 758, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 769, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다
