2024-01-25 13:38:46,355 INFO    MainThread:54944 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-01-25 13:38:46,356 INFO    MainThread:54944 [wandb_setup.py:_flush():76] Configure stats pid to 54944
2024-01-25 13:38:46,356 INFO    MainThread:54944 [wandb_setup.py:_flush():76] Loading settings from C:\Users\jsjon\.config\wandb\settings
2024-01-25 13:38:46,356 INFO    MainThread:54944 [wandb_setup.py:_flush():76] Loading settings from c:\Users\jsjon\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\settings
2024-01-25 13:38:46,356 INFO    MainThread:54944 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-25 13:38:46,356 INFO    MainThread:54944 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'New Code\\Data_extrapolative copy.py', 'program_abspath': 'c:\\Users\\jsjon\\OneDrive\\SKKU\\연구자료\\Catalyst AI_rev\\New Code\\Data_extrapolative copy.py', 'program': 'c:\\Users\\jsjon\\OneDrive\\SKKU\\연구자료\\Catalyst AI_rev\\New Code\\Data_extrapolative copy.py'}
2024-01-25 13:38:46,359 INFO    MainThread:54944 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\jsjon\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240125_133846-tfekm666\logs\debug.log
2024-01-25 13:38:46,360 INFO    MainThread:54944 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\jsjon\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240125_133846-tfekm666\logs\debug-internal.log
2024-01-25 13:38:46,360 INFO    MainThread:54944 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001ACD2D450D0>
2024-01-25 13:38:46,360 INFO    MainThread:54944 [wandb_init.py:init():566] calling init triggers
2024-01-25 13:38:46,360 INFO    MainThread:54944 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-01-25 13:38:46,360 INFO    MainThread:54944 [wandb_init.py:init():616] starting backend
2024-01-25 13:38:46,360 INFO    MainThread:54944 [wandb_init.py:init():620] setting up manager
2024-01-25 13:38:46,367 INFO    MainThread:54944 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-01-25 13:38:46,370 INFO    MainThread:54944 [wandb_init.py:init():628] backend started and connected
2024-01-25 13:38:46,391 INFO    MainThread:54944 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-25 13:38:46,392 INFO    MainThread:54944 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-25 13:38:46,392 INFO    MainThread:54944 [wandb_init.py:init():720] updated telemetry
2024-01-25 13:38:46,455 INFO    MainThread:54944 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-01-25 13:38:47,020 INFO    MainThread:54944 [wandb_run.py:_on_init():2254] communicating current version
2024-01-25 13:38:47,069 INFO    MainThread:54944 [wandb_run.py:_on_init():2263] got version response 
2024-01-25 13:38:47,069 INFO    MainThread:54944 [wandb_init.py:init():804] starting run threads in backend
2024-01-25 13:38:59,786 INFO    MainThread:54944 [wandb_run.py:_console_start():2233] atexit reg
2024-01-25 13:38:59,787 INFO    MainThread:54944 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-01-25 13:38:59,787 INFO    MainThread:54944 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-01-25 13:38:59,787 INFO    MainThread:54944 [wandb_run.py:_redirect():2178] Redirects installed.
2024-01-25 13:38:59,788 INFO    MainThread:54944 [wandb_init.py:init():847] run started, returning control to user process
2024-01-25 13:38:59,792 INFO    MainThread:54944 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:38:59,792 INFO    MainThread:54944 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:39:22,049 INFO    MainThread:54944 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:39:22,054 INFO    MainThread:54944 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:39:22,055 INFO    MainThread:54944 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:39:26,278 INFO    MainThread:54944 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:39:26,281 INFO    MainThread:54944 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:39:26,281 INFO    MainThread:54944 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:39:26,864 INFO    MainThread:54944 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:39:26,864 INFO    MainThread:54944 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:39:26,864 INFO    MainThread:54944 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:39:39,945 INFO    MainThread:54944 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:39:39,946 INFO    MainThread:54944 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:39:39,947 INFO    MainThread:54944 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:39:41,833 INFO    MainThread:54944 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:41:50,244 WARNING MsgRouterThr:54944 [router.py:message_loop():77] message_loop has been closed
2024-01-25 13:41:52,429 INFO    MainThread:54944 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:41:52,429 INFO    MainThread:54944 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:43:58,475 INFO    MainThread:54944 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:43:58,487 INFO    MainThread:54944 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:43:58,487 INFO    MainThread:54944 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:47:27,757 INFO    MainThread:54944 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:47:27,757 INFO    MainThread:54944 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:47:27,757 INFO    MainThread:54944 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:47:29,813 INFO    MainThread:54944 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:47:29,825 INFO    MainThread:54944 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-25 13:47:29,825 INFO    MainThread:54944 [wandb_init.py:_pause_backend():437] pausing backend
2024-01-25 13:47:37,900 INFO    MainThread:54944 [wandb_init.py:_resume_backend():442] resuming backend
2024-01-25 13:47:37,935 INFO    MainThread:54944 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-01-25 13:47:37,936 INFO    MainThread:54944 [wandb_setup.py:_flush():76] Configure stats pid to 54944
2024-01-25 13:47:37,936 INFO    MainThread:54944 [wandb_setup.py:_flush():76] Loading settings from C:\Users\jsjon\.config\wandb\settings
2024-01-25 13:47:37,936 INFO    MainThread:54944 [wandb_setup.py:_flush():76] Loading settings from c:\Users\jsjon\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\settings
2024-01-25 13:47:37,936 INFO    MainThread:54944 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-25 13:47:37,936 INFO    MainThread:54944 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'New Code\\Data_extrapolative copy.py', 'program_abspath': 'c:\\Users\\jsjon\\OneDrive\\SKKU\\연구자료\\Catalyst AI_rev\\New Code\\Data_extrapolative copy.py', 'program': 'c:\\Users\\jsjon\\OneDrive\\SKKU\\연구자료\\Catalyst AI_rev\\New Code\\Data_extrapolative copy.py'}
2024-01-25 13:47:37,937 INFO    MainThread:54944 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\jsjon\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240125_134737-89t7rlz4\logs\debug.log
2024-01-25 13:47:37,937 INFO    MainThread:54944 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\jsjon\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240125_134737-89t7rlz4\logs\debug-internal.log
2024-01-25 13:47:37,937 INFO    MainThread:54944 [wandb_init.py:init():566] calling init triggers
2024-01-25 13:47:37,937 INFO    MainThread:54944 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-01-25 13:47:37,937 INFO    MainThread:54944 [wandb_init.py:init():591] re-initializing run, found existing run on stack: tfekm666
2024-01-25 13:47:38,072 ERROR   MainThread:54944 [wandb_init.py:init():1204] error
Traceback (most recent call last):
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1176, in init
    run = wi.init()
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 601, in init
    latest_run.finish()
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 420, in wrapper
    return func(self, *args, **kwargs)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 361, in wrapper
    return func(self, *args, **kwargs)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1953, in finish
    return self._finish(exit_code, quiet)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1961, in _finish
    tel.feature.finish = True
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\lib\telemetry.py", line 42, in __exit__
    self._run._telemetry_callback(self._obj)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 758, in _telemetry_callback
    self._telemetry_flush()
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 769, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 101, in _publish_telemetry
    self._publish(rec)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "c:\Users\jsjon\anaconda3\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] 현재 연결은 원격 호스트에 의해 강제로 끊겼습니다
