2024-03-05 09:56:54,037 INFO    MainThread:36180 [wandb_setup.py:_flush():76] Current SDK version is 0.16.3
2024-03-05 09:56:54,037 INFO    MainThread:36180 [wandb_setup.py:_flush():76] Configure stats pid to 36180
2024-03-05 09:56:54,037 INFO    MainThread:36180 [wandb_setup.py:_flush():76] Loading settings from C:\Users\OJH\.config\wandb\settings
2024-03-05 09:56:54,037 INFO    MainThread:36180 [wandb_setup.py:_flush():76] Loading settings from c:\Users\OJH\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\settings
2024-03-05 09:56:54,038 INFO    MainThread:36180 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-05 09:56:54,038 INFO    MainThread:36180 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-05 09:56:54,038 INFO    MainThread:36180 [wandb_init.py:_log_setup():526] Logging user logs to c:\Users\OJH\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240305_095654-soc9wjry\logs\debug.log
2024-03-05 09:56:54,038 INFO    MainThread:36180 [wandb_init.py:_log_setup():527] Logging internal logs to c:\Users\OJH\OneDrive\SKKU\연구자료\Catalyst AI_rev\New Code\wandb\run-20240305_095654-soc9wjry\logs\debug-internal.log
2024-03-05 09:56:54,038 INFO    MainThread:36180 [wandb_init.py:init():566] calling init triggers
2024-03-05 09:56:54,038 INFO    MainThread:36180 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-05 09:56:54,038 INFO    MainThread:36180 [wandb_init.py:init():591] re-initializing run, found existing run on stack: kvmlx08w
2024-03-05 09:56:54,039 INFO    MainThread:36180 [wandb_run.py:_finish():1970] finishing run jonghwan_oh/Model prediction/kvmlx08w
2024-03-05 09:56:54,039 INFO    MainThread:36180 [jupyter.py:save_history():445] not saving jupyter history
2024-03-05 09:56:54,039 INFO    MainThread:36180 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-05 09:56:54,040 INFO    MainThread:36180 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-05 09:56:54,040 INFO    MainThread:36180 [wandb_run.py:_atexit_cleanup():2210] got exitcode: 0
2024-03-05 09:56:54,040 INFO    MainThread:36180 [wandb_run.py:_restore():2193] restore
2024-03-05 09:56:54,040 INFO    MainThread:36180 [wandb_run.py:_restore():2199] restore done
2024-03-05 09:57:25,475 INFO    MainThread:36180 [wandb_run.py:_footer_history_summary_info():3866] rendering history
2024-03-05 09:57:25,478 INFO    MainThread:36180 [wandb_run.py:_footer_history_summary_info():3898] rendering summary
2024-03-05 09:57:25,488 INFO    MainThread:36180 [wandb_run.py:_footer_sync_info():3825] logging synced files
2024-03-05 09:57:25,823 INFO    MainThread:36180 [wandb_init.py:init():616] starting backend
2024-03-05 09:57:25,823 INFO    MainThread:36180 [wandb_init.py:init():620] setting up manager
2024-03-05 09:57:25,828 INFO    MainThread:36180 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-03-05 09:57:25,829 INFO    MainThread:36180 [wandb_init.py:init():628] backend started and connected
2024-03-05 09:57:25,838 INFO    MainThread:36180 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-05 09:57:25,838 INFO    MainThread:36180 [wandb_run.py:_label_probe_notebook():1305] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-05 09:57:25,838 INFO    MainThread:36180 [wandb_init.py:init():720] updated telemetry
2024-03-05 09:57:25,871 INFO    MainThread:36180 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-05 09:57:27,133 INFO    MainThread:36180 [wandb_run.py:_on_init():2262] communicating current version
2024-03-05 09:57:27,418 INFO    MainThread:36180 [wandb_run.py:_on_init():2271] got version response 
2024-03-05 09:57:27,419 INFO    MainThread:36180 [wandb_init.py:init():804] starting run threads in backend
2024-03-05 09:57:33,442 INFO    MainThread:36180 [wandb_run.py:_console_start():2241] atexit reg
2024-03-05 09:57:33,442 INFO    MainThread:36180 [wandb_run.py:_redirect():2096] redirect: wrap_raw
2024-03-05 09:57:33,442 INFO    MainThread:36180 [wandb_run.py:_redirect():2161] Wrapping output streams.
2024-03-05 09:57:33,442 INFO    MainThread:36180 [wandb_run.py:_redirect():2186] Redirects installed.
2024-03-05 09:57:33,443 INFO    MainThread:36180 [wandb_init.py:init():847] run started, returning control to user process
